# Generated by Django 5.2 on 2025-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('button', 'Button'), ('input', 'Input'), ('table', 'Table'), ('text', 'Text'), ('container', 'Container'), ('image', 'Image'), ('chart', 'Chart'), ('form', 'Form')], max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
