# Generated by Django 5.2.1 on 2025-05-23 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_component_type_alter_page_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('Button', 'Button'), ('Input', 'Input'), ('Table', 'Table'), ('Text', 'Text'), ('Container', 'Container'), ('Image', 'Image'), ('Chart', 'Chart'), ('Form', 'Form')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('name', 'owner')},
        ),
    ]
