# Generated by Django 5.2.1 on 2025-05-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250523_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='device_type',
            field=models.CharField(choices=[('web', 'Web'), ('tablet', 'Tablet'), ('phone', 'Phone')], default='web', max_length=10),
        ),
    ]
