# Generated by Django 5.2.1 on 2025-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('Button', 'Button'), ('Input', 'Input'), ('Text', 'Text'), ('Table', 'Table'), ('Form', 'Form'), ('Select', 'Select'), ('CurrencyInput', 'Currency Input'), ('DatePicker', 'Date Picker'), ('FilePicker', 'File Picker'), ('PhoneInput', 'Phone Input'), ('RichTextEditor', 'Rich Text Editor'), ('ButtonGroup', 'Button Group'), ('IconButton', 'Icon Button'), ('MenuButton', 'Menu Button'), ('Chart', 'Chart'), ('Custom', 'Custom'), ('Iframe', 'Iframe'), ('List', 'List'), ('MapChart', 'Map Chart'), ('StatsBox', 'Stats Box'), ('Container', 'Container'), ('Divider', 'Divider'), ('JSONForm', 'JSON Form'), ('Modal', 'Modal'), ('Tabs', 'Tabs'), ('Audio', 'Audio'), ('DocumentViewer', 'Document Viewer'), ('Image', 'Image'), ('Video', 'Video'), ('Checkbox', 'Checkbox'), ('CheckboxGroup', 'Checkbox Group'), ('RadioGroup', 'Radio Group'), ('Switch', 'Switch'), ('SwitchGroup', 'Switch Group'), ('CategorySlider', 'Category Slider'), ('NumberSlider', 'Number Slider'), ('RangeSlider', 'Range Slider'), ('Map', 'Map'), ('Progress', 'Progress'), ('Rating', 'Rating')], max_length=50),
        ),
    ]
