# Generated by Django 5.1.5 on 2025-06-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_component_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('PSO_LAYOUT', 'PSO Layout Optimization'), ('NLP_COMPONENT', 'NLP Component Generation'), ('NLP_TRANSLATE', 'NLP Translation'), ('COLOR_OPTIMIZE', 'Color Optimization')], max_length=50)),
                ('input_hash', models.CharField(max_length=64, unique=True)),
                ('result_data', models.JSONField()),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['cache_type', 'input_hash'], name='api_aicache_cache_t_31c949_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nlp_keywords', models.JSONField(default=list)),
                ('template_config', models.JSONField(default=dict)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('generated_component', models.JSONField()),
                ('user_feedback', models.IntegerField(blank=True, choices=[(1, '差'), (2, '一般'), (3, '好'), (4, '很好'), (5, '完美')], null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('corrected_component', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_training_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_type', models.CharField(choices=[('PSO', 'Particle Swarm Optimization'), ('NLP', 'Natural Language Processing'), ('LAYOUT', 'Layout Optimization'), ('COLOR', 'Color Scheme Optimization')], max_length=50)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('performance_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='api.page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_optimizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
