services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lcdp_db}
      POSTGRES_USER: ${POSTGRES_USER:-lcdp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lcdp_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lcdp_network

  backend:
    build:
      context: ./LCDPBackend
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lcdp_db}
      POSTGRES_USER: ${POSTGRES_USER:-lcdp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lcdp_password}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DEBUG: ${DEBUG:-True}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
    volumes:
      - ./LCDPBackend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - lcdp_network
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./LCDPFront/lcdp-front
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000/api}
    volumes:
      - ./LCDPFront/lcdp-front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - lcdp_network
    command: ["npm", "start"]

volumes:
  postgres_data:

networks:
  lcdp_network:
    driver: bridge 